{{- if .Values.gameService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sudoku-ultra.labels" . | nindent 4 }}
    app.kubernetes.io/component: game-service
spec:
  selector:
    {{- include "sudoku-ultra.selectorLabels" (dict "component" "game-service" "root" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.gameService.service.port }}
      targetPort: http
      protocol: TCP
  type: ClusterIP
{{- end }}
