{{- if .Values.global }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sudoku-ultra.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.global.jwtSecret | quote }}
  internal-secret: {{ .Values.global.internalSecret | quote }}
{{- end }}
